# Generated by Django 3.2.1 on 2021-05-31 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifuploads',
            name='upload_date',
        ),
    ]
