# Generated by Django 3.2.1 on 2021-10-05 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kblock', '0004_alter_certifuploads_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifuploads',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
