# Generated by Django 3.1.13 on 2021-10-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0006_auto_20211009_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
