# Generated by Django 3.1.13 on 2021-10-09 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0007_auto_20211009_2235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdf',
        ),
    ]
