# Generated by Django 3.1.13 on 2021-10-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0009_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='message',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='subject',
        ),
        migrations.AddField(
            model_name='pdf',
            name='degree',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdf',
            name='edu',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdf',
            name='phone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdf',
            name='tech',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdf',
            name='work',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdf',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
