# Generated by Django 3.1.13 on 2021-10-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0010_auto_20211009_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='degree',
            new_name='datestart',
        ),
        migrations.RenameField(
            model_name='pdf',
            old_name='edu',
            new_name='role',
        ),
    ]
