# Generated by Django 3.1.13 on 2021-10-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0011_auto_20211009_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='phone',
            new_name='dateend',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='tech',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='work',
        ),
    ]
