# Generated by Django 3.1.13 on 2021-10-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0012_auto_20211010_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='pdf',
            name='slug',
            field=models.CharField(default='ok', max_length=12),
        ),
    ]
