# Generated by Django 3.1.13 on 2021-10-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0015_auto_20211010_1857'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModel',
            new_name='Certificate',
        ),
    ]
