# Generated by Django 3.1.13 on 2021-10-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0016_auto_20211010_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.AddField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
