# Generated by Django 3.1.13 on 2021-10-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0017_auto_20211010_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ok', max_length=12)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='pdf',
        ),
    ]
