# Generated by Django 3.1.13 on 2021-10-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0018_auto_20211010_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='name',
        ),
    ]
