# Generated by Django 3.1.13 on 2021-10-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0020_certificate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(default='ok', max_length=100),
        ),
    ]
