# Generated by Django 3.1.13 on 2021-10-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0021_auto_20211010_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='web',
            field=models.CharField(default='ok', max_length=1000),
        ),
    ]
