# Generated by Django 3.1.13 on 2021-10-31 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0022_certificate_web'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertifUploads',
        ),
    ]
