# Generated by Django 3.1.13 on 2021-12-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0023_delete_certifuploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkhash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orihash', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
