# Generated by Django 3.1.13 on 2021-12-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0025_auto_20211211_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkhash',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='check/'),
        ),
    ]
