# Generated by Django 3.1.13 on 2021-12-11 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0026_auto_20211211_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkhash',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkhash',
            name='file',
            field=models.FileField(null=True, upload_to='check/'),
        ),
    ]
