# Generated by Django 3.1.13 on 2021-12-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0028_auto_20211211_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkhash',
        ),
        migrations.AddField(
            model_name='certificate',
            name='hash',
            field=models.CharField(default='ok', max_length=300),
        ),
    ]
