# Generated by Django 3.1.13 on 2021-12-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0029_auto_20211214_2307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.AddField(
            model_name='pdf',
            name='hash',
            field=models.CharField(default='ok', max_length=300),
        ),
        migrations.AddField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='pdf',
            name='web',
            field=models.CharField(default='ok', max_length=1000),
        ),
    ]
