# Generated by Django 3.1.13 on 2021-12-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kblock', '0030_auto_20211215_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ok', max_length=100)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('hash', models.CharField(default='ok', max_length=300)),
                ('web', models.CharField(default='ok', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='web',
        ),
    ]
